package com.yb

import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.functions._
class Agg {

  val spark = SparkSession.builder
    .appName("My Spark Application") // optional and will be autogenerated if not specified
    .master("local[*]") // only for demo and testing purposes, use spark-submit instead
    //.enableHiveSupport()              // self-explanatory, isn't it?
    .config("spark.sql.warehouse.dir", "target/spark-warehouse")
    .getOrCreate()

  val df = spark.read.format("csv").option("header", "true").load("csvfile.csv")

  df.select(countDistinct("a"))
  df.select(approx_count_distinct(""))

}
